export const usersActionType = {
  SET_USER_BEGIN: "SET_USER_BEGIN",
  SET_USER_SUCCESS: "SET_USER_SUCCESS",
  SET_USER_FAILURE: "SET_USER_FAILURE",

  FETCH_ALL_USERS: "FETCH_ALL_USERS",
  FETCH_ALL_CHATS: "FETCH_ALL_CHATS",
}
